// Types of packets
#define MM_PACKET_READ 0x03
#define MM_PACKET_WRITE 0x10
#define MM_PACKET_MODEM_REPLY 0x7f

// Codes of data
#define MM_DCODE_GET_BEACON_STATE 0x0003
#define MM_DCODE_SET_ADDRESS 0x0101
#define MM_DCODE_ROBOT_STOP 0x0403
#define MM_DCODE_ROBOT_CTRL 0x1000
#define MM_DCODE_RAW_DISTANCES_LAST 0x4000
#define MM_DCODE_RAW_DISTANCES_ALL 0x4001
#define MM_DCODE_COORDINATES 0x4100
#define MM_DCODE_MODEM_CONFIG 0x5000
#define MM_DCODE_SUBMAP_CONFIG_BASE 0x6000
#define MM_DCODE_SLEEP_WAKE 0xb006

// Access modes
#define MM_ACCESS_MODE_DEFAULT 0
#define MM_ACCESS_MODE_REMOTE 1
#define MM_ACCESS_MODE_BUFFER 2