@startuml dashboard_command_example;
participant "Hedgehog" as A
participant "Pololu" as B
group Position [stream packet]
    A-> B: 0x47 [send position]
    activate B
    B --> A: {x,y,z}
    deactivate B
end

group Commande [Request/Response packet]
    B -> A: 0x48 [I am ready]
    activate B
    A -> B: 0x4a {data}
    deactivate B
    B -> A: 0x48 [I am ready]
    activate B
    A -> B: 0x4a {data}
    deactivate B
end
@enduml
